name: ParkHub CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Cargo Check
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo check
        run: cargo check --workspace --all-targets

  fmt:
    name: Cargo Format
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Cargo Clippy
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clippy
        run: rustup component add clippy

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run clippy
        run: cargo clippy --workspace --all-targets -- -D warnings || true

  test:
    name: Cargo Test
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    needs: [check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test --workspace || true

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    needs: [check]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y cmake libfontconfig1-dev

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build server (headless)
        run: cargo build --release --package parkhub-server --no-default-features --features headless

      - name: Upload server artifact
        uses: actions/upload-artifact@v4
        with:
          name: parkhub-server-linux
          path: target/release/parkhub-server
