name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  ATTIC_CACHE: default
  ATTIC_SERVER: http://192.168.178.201:31580

jobs:
  check:
    name: Quality Checks
    runs-on: nixos
    steps:
      - name: Format + Clippy
        run: |
          set -euxo pipefail
          cd /home/florian/parkhub
          git fetch origin
          git checkout $GITHUB_REF_NAME
          git reset --hard origin/$GITHUB_REF_NAME

          # Configure Attic as Nix substituter for cached builds
          attic use default 2>/dev/null || true

          echo '=== Format Check ==='
          nix build .#checks.x86_64-linux.fmt --no-link 2>&1 | tail -5

          echo '=== Clippy ==='
          nix build .#checks.x86_64-linux.clippy --no-link 2>&1 | tail -5

          echo 'All checks passed!'

  test:
    name: Tests
    runs-on: nixos
    steps:
      - name: Run Tests
        run: |
          set -euxo pipefail
          cd /home/florian/parkhub
          git fetch origin
          git checkout $GITHUB_REF_NAME
          git reset --hard origin/$GITHUB_REF_NAME

          attic use default 2>/dev/null || true

          echo '=== Tests ==='
          nix build .#checks.x86_64-linux.tests --no-link 2>&1 | tail -10

          echo 'All tests passed!'

  build-deploy:
    name: Build & Deploy
    runs-on: nixos
    needs: [check, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Build, push & deploy
        run: |
          set -euxo pipefail
          cd /home/florian/parkhub
          git fetch origin main
          git checkout main
          git reset --hard origin/main

          # Configure Attic substituter
          attic use default 2>/dev/null || true

          # Bump CalVer version
          ./scripts/version.sh next

          # Update Cargo.lock after version bump
          cargo update --workspace

          VERSION=$(cat VERSION)

          echo "Building ParkHub v${VERSION}..."

          # Build container image via Nix
          STREAM_SCRIPT=$(nix build .#streamImage --no-link --print-out-paths 2>&1 | tail -1)

          # Push build closure to Attic cache
          attic push default "$STREAM_SCRIPT" 2>/dev/null || true

          # Push to registry via NodePort
          REGISTRY="192.168.178.201:31584"
          "$STREAM_SCRIPT" | skopeo copy \
            --insecure-policy \
            docker-archive:/dev/stdin \
            "docker://${REGISTRY}/parkhub:v${VERSION}" \
            --dest-tls-verify=false

          echo "Pushed parkhub:v${VERSION} to registry"

          # Commit version bump + updated lock
          git config user.name "CI Bot"
          git config user.email "ci@parkhub.local"
          git add VERSION Cargo.toml Cargo.lock .build-number
          if ! git diff --cached --quiet; then
            git commit -m "chore(release): v${VERSION} [skip ci]"
            git push origin main
            echo "Version bump committed"
          fi

          echo "Flux will auto-deploy within ~1 minute"

  audit:
    name: Security Audit
    runs-on: nixos
    steps:
      - name: Cargo audit
        run: |
          set -euxo pipefail
          cd /home/florian/parkhub
          git fetch origin main
          git checkout main
          git reset --hard origin/main

          attic use default 2>/dev/null || true

          nix build .#checks.x86_64-linux.audit --no-link 2>&1 | tail -10
          echo 'Audit complete'
