name: ParkHub CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check, Format & Test
    runs-on: nixos
    steps:
      - name: Build & Test
        run: |
          set -euxo pipefail
          cd /home/florian/parkhub
          git fetch origin
          git checkout $GITHUB_REF_NAME
          git reset --hard origin/$GITHUB_REF_NAME

          # Check
          cargo check --workspace --all-targets

          # Format
          cargo fmt --all -- --check

          # Clippy (warn only)
          cargo clippy --workspace --all-targets 2>&1 || true

          # Tests
          cargo test --workspace

          echo "✅ All checks passed"
