name: ParkHub CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Quality Checks
    runs-on: nixos
    steps:
      - name: Format + Clippy + Tests
        run: |
          set -euxo pipefail
          cd /home/florian/parkhub
          git fetch origin
          git checkout $GITHUB_REF_NAME
          git reset --hard origin/$GITHUB_REF_NAME

          # Configure Attic cache
          attic use default 2>/dev/null || true

          echo '=== Format Check ==='
          cargo fmt --all -- --check

          echo '=== Clippy ==='
          cargo clippy --package parkhub-server --package parkhub-common \
            --no-default-features --features headless \
            -- -D warnings \
            -A unused_imports -A unused_variables -A dead_code 2>&1 || true

          echo '=== Tests ==='
          cargo test --package parkhub-server --package parkhub-common \
            --no-default-features --features headless

          echo '✅ All checks passed'

  build:
    name: Build Image
    runs-on: nixos
    needs: check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Build & Push
        run: |
          set -euxo pipefail
          cd /home/florian/parkhub
          git fetch origin main
          git checkout main
          git reset --hard origin/main

          attic use default 2>/dev/null || true

          VERSION=$(cat VERSION)
          echo "Building ParkHub v${VERSION}..."

          # Build container image via Nix
          STREAM_SCRIPT=$(nix build .#streamImage --no-link --print-out-paths 2>&1 | tail -1)

          # Push to Attic cache
          attic push default "$STREAM_SCRIPT" 2>/dev/null || true

          # Push to registry
          REGISTRY="192.168.178.201:31584"
          "$STREAM_SCRIPT" | skopeo copy \
            --insecure-policy \
            docker-archive:/dev/stdin \
            "docker://${REGISTRY}/parkhub:v${VERSION}" \
            --dest-tls-verify=false

          echo "Pushed parkhub:v${VERSION} to registry"

  audit:
    name: Security Audit
    runs-on: nixos
    steps:
      - name: Cargo audit
        run: |
          set -euxo pipefail
          cd /home/florian/parkhub
          git fetch origin main
          git checkout main
          git reset --hard origin/main

          attic use default 2>/dev/null || true

          nix develop --command cargo audit || true
          echo 'Audit complete'
